---
- name: Create ArchLinux mirror directory
  ansible.builtin.file:
    path: /srv/archlinux
    state: directory
    owner: mirrors
    group: mirrors
    mode: "0755"
  tags:
    - archlinux

- name: Copy ArchLinux timer, service and script files
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  loop:
    - { src: "distros/ArchLinux/repository/confd/archlinux-mirror-sync.timer", dest: "/etc/systemd/system/archlinux-mirror-sync.timer", mode: "0644" }
    - { src: "distros/ArchLinux/repository/confd/archlinux-mirror-sync.service", dest: "/etc/systemd/system/archlinux-mirror-sync.service", mode: "0644" }
    - { src: "distros/ArchLinux/repository/scripts/archlinux-syncrepo.sh", dest: "/usr/local/bin/archlinux-syncrepo.sh", mode: "0755" }
  tags:
    - archlinux

- name: Start ArchLinux mirror timer service
  ansible.builtin.systemd_service:
    name: archlinux-mirror-sync.timer
    enabled: true
    state: started
    daemon_reload: true
  tags:
    - archlinux
...
