---
- name: Copy Debian repository timer, service and script files
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  loop:
    - { src: "distros/Debian/repository/confd/debian-mirror-sync.timer", dest: "/etc/systemd/system/debian-mirror-sync.timer", mode: "0644" }
    - { src: "distros/Debian/repository/confd/debian-mirror-sync.service", dest: "/etc/systemd/system/debian-mirror-sync.service", mode: "0644" }
    - { src: "distros/Debian/repository/scripts/debian-mirror-sync-check.sh", dest: "/usr/local/bin/debian-mirror-sync-check.sh", mode: "0755" }

- name: Copy Debian ISO timer and service files
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  loop:
    - { src: "distros/Debian/ISO/confd/debian-cd-mirror-sync.timer", dest: "/etc/systemd/system/debian-cd-mirror-sync.timer", mode: "0644" }
    - { src: "distros/Debian/ISO/confd/debian-cd-mirror-sync.service", dest: "/etc/systemd/system/debian-cd-mirror-sync.service", mode: "0644" }

- name: Start Debian mirror timer services
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    enabled: true
    state: started
    daemon_reload: true
  loop:
    - debian-mirror-sync.timer
    - debian-cd-mirror-sync.timer
...
