---
- name: Create nginx configuration directory for mirrors
  ansible.builtin.file:
    path: /etc/nginx/conf.d
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Deploy mirror configuration on nginx
  ansible.builtin.template:
    src: "templates/mirror.conf.jinja"
    dest: "/etc/nginx/conf.d/mirror.conf"
    owner: root
    group: root
    mode: "0644"
  notify: reload nginx

...
