apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: https-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: lidsol@protonmail.com
    privateKeySecretRef:
      name: https-issuer-acme-privatekey
    solvers:
    - http01:
        ingress:
          class: nginx
