---
    - name: Install unattended-upgrades and apt-list changes
      ansible.builtin.apt:
        name:
          - unattended-upgrades
          - apt-listchanges
        state: present
        update_cache: yes

    - name: Enable auto updates
      ansible.builtin.debconf:
        name: unattended-upgrades
        question: unattended-upgrades/enable_auto_updates
        value: 'true'
        vtype: boolean

    - name: DPKG reconfigure
      ansible.builtin.command: dpkg-reconfigure -f noninteractive unattended-upgrades
      args:
        creates: /etc/apt/apt.conf.d/20auto-upgrades
...
